#Theme Info
theme                  : "minimal-mistakes-jekyll"
#remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

#Basic Site Info
locale: "en-US"
url: "https://BraydenArcher.github.io"
repository: "BraydenArcher/BraydenArcher.github.io"
breadcrumbs: true


#Basic Brayden Info
title: Brayden Archer
author: brayden_archer


#Default config values that came with the theme
# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache