#Theme Info
theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

#Basic Site Info
locale: "en-US"
url: "https://BraydenArcher.github.io"
repository: "BraydenArcher/BraydenArcher.github.io"
breadcrumbs: true


#Basic Brayden Info
title: Brayden Archer
author: brayden_archer