#Theme Info
theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

#Basic Site Info
locale: "en-US"
url: "https://BraydenArcher.github.io"
repository: "BraydenArcher/BraydenArcher.github.io"
breadcrumbs: true


#Basic Brayden Info
title: Brayden Archer
author: brayden_archer


#Stuff for GitHub
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache