theme: jekyll-theme-minimal
title: [Brayden Archer]
description: [A website/blog to show off some of the projects I do and learn about on my own time]

#Author Info
author:
  name: "Brayden Archer"
  avatar: "assets/images/Headshot.JPG"
  location: "Baltimore, MD"
  bio: "A website/blog to show off some of the projects I do and learn ab\
out on my own time"